"""Create Infolink table

Revision ID: 04355214319d
Revises: afe0e6656245
Create Date: 2024-09-28 16:15:04.515892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04355214319d'
down_revision = 'afe0e6656245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infolink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memo_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memo_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memo_tag_id'), ['tag_id'], unique=False)

    with op.batch_alter_table('mymemo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mymemo_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mymemo_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mymemo_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mymemo_tag_id'), ['tag_id'], unique=False)

    with op.batch_alter_table('project_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_image_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('project_memo_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_memo_image_memo_id'), ['memo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_memo_image_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_project_id'))

    with op.batch_alter_table('project_memo_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_memo_image_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_memo_image_memo_id'))

    with op.batch_alter_table('project_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_image_project_id'))

    with op.batch_alter_table('mymemo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mymemo_tag_id'))
        batch_op.drop_index(batch_op.f('ix_mymemo_project_id'))
        batch_op.drop_index(batch_op.f('ix_mymemo_product_id'))
        batch_op.drop_index(batch_op.f('ix_mymemo_parent_id'))

    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memo_tag_id'))
        batch_op.drop_index(batch_op.f('ix_memo_project_id'))
        batch_op.drop_index(batch_op.f('ix_memo_parent_id'))

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_project_id'))

    op.drop_table('infolink')
    # ### end Alembic commands ###
