"""Set project_id to nullable in Memo model

Revision ID: 129bc6228219
Revises: 0fb4e263cbdc
Create Date: 2024-10-08 10:27:13.879989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129bc6228219'
down_revision = '0fb4e263cbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
