"""Add timezone-aware defaults to due_date and finished_date

Revision ID: 196aa0a33749
Revises: 8acfaa30ca26
Create Date: 2024-08-28 16:19:32.502073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196aa0a33749'
down_revision = '8acfaa30ca26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('finished_date')

    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
