"""Switch MyMemo link to Note model

Revision ID: 1bdf6a23c6e2
Revises: c0623356280c
Create Date: 2026-01-11 18:58:38.676933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdf6a23c6e2'
down_revision = 'c0623356280c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mymemo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_note_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_mymemo_linked_memo_id_memo', type_='foreignkey')
        batch_op.drop_column('linked_memo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mymemo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_memo_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_mymemo_linked_memo_id_memo', 'memo', ['linked_memo_id'], ['id'])
        batch_op.drop_column('linked_note_id')

    # ### end Alembic commands ###
