"""Change Memo.created_at to DateTime

Revision ID: 23efbdc721c9
Revises: 1f2d8496d30d
Create Date: 2024-08-18 12:46:55.824557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23efbdc721c9'
down_revision = '1f2d8496d30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
