from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca3c32518c2'
down_revision = '04355214319d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Step 1: Add columns as nullable=True to allow for existing data
    with op.batch_alter_table('infolink', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=True))
    
    # Step 2: Update existing data with a default category/subcategory
    connection = op.get_bind()
    
    # Insert a default category and subcategory (if needed)
    connection.execute(
        sa.text("INSERT INTO category (id, name) VALUES (1, 'Default Category') ON CONFLICT DO NOTHING")
    )
    connection.execute(
        sa.text("INSERT INTO subcategory (id, name, category_id) VALUES (1, 'Default Subcategory', 1) ON CONFLICT DO NOTHING")
    )

    # Set the default category and subcategory for existing Infolink rows
    connection.execute(
        sa.text("UPDATE infolink SET category_id = 1, subcategory_id = 1 WHERE category_id IS NULL OR subcategory_id IS NULL")
    )

    # Step 3: Add foreign key constraints after data migration
    with op.batch_alter_table('infolink', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_infolink_category_id', 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_infolink_subcategory_id', 'subcategory', ['subcategory_id'], ['id'])
    
    # Step 4: Alter the columns to be non-nullable after the data update
    with op.batch_alter_table('infolink', schema=None) as batch_op:
        batch_op.alter_column('category_id', nullable=False)
        batch_op.alter_column('subcategory_id', nullable=False)

    # Drop old columns if they existed
    with op.batch_alter_table('infolink', schema=None) as batch_op:
        if batch_op.has_column('category'):
            batch_op.drop_column('category')
        if batch_op.has_column('subcategory'):
            batch_op.drop_column('subcategory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('infolink', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('subcategory', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_infolink_category_id', type_='foreignkey')
        batch_op.drop_constraint('fk_infolink_subcategory_id', type_='foreignkey')
        batch_op.drop_column('subcategory_id')
        batch_op.drop_column('category_id')

    op.drop_table('subcategory')
    op.drop_table('category')
    # ### end Alembic commands ###
