"""Add MemoImage model

Revision ID: 332f02347018
Revises: 11feea964dca
Create Date: 2026-02-17 21:09:16.660950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332f02347018'
down_revision = '11feea964dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memo_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memo_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memo_id'], ['memo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memo_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memo_image_memo_id'), ['memo_id'], unique=False)

    op.drop_table('test_results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test_title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('gsheet_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('sheet_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cell_range', sa.VARCHAR(length=50), nullable=True),
    sa.Column('main_title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sub_title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('chart_settings', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('html_template', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memo_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memo_image_memo_id'))

    op.drop_table('memo_image')
    # ### end Alembic commands ###
