"""empty message

Revision ID: 54a5170fd70e
Revises: 4d30c9ec1ea3
Create Date: 2025-10-09 14:11:30.491151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a5170fd70e'
down_revision = '4d30c9ec1ea3'
branch_labels = None
depends_on = None


def upgrade():
    # 1. is_completed 컬럼을 'nullable=True'로 먼저 추가합니다. (NULL 허용)
    op.add_column('project', sa.Column('is_completed', sa.Boolean(), nullable=True))

    # 2. 기존 행의 is_completed 값을 모두 False로 채웁니다.
    #    (기존 데이터에 NULL이 아닌 값이 생기도록 만듭니다.)
    op.execute("UPDATE project SET is_completed = 0") # SQLite에서 True는 1, False는 0

    # 3. 컬럼의 nullable 제약 조건을 False로 변경합니다. (NOT NULL 강제)
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('is_completed', existing_type=sa.Boolean(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
