"""Add product relationship to MyMemo

Revision ID: 5787d119892c
Revises: 23efbdc721c9
Create Date: 2024-08-19 07:38:54.309564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5787d119892c'
down_revision = '23efbdc721c9'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('my_memo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_my_memo_product', 'product', ['product_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_memo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
