"""Add meta_data and linked_memo_id to MyMemo

Revision ID: c0623356280c
Revises: f12c9c4d0f90
Create Date: 2026-01-11 17:09:40.371611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0623356280c'
down_revision = 'f12c9c4d0f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mymemo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('linked_memo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mymemo_linked_memo_id_memo', 'memo', ['linked_memo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mymemo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mymemo_linked_memo_id_memo', type_='foreignkey')
        batch_op.drop_column('linked_memo_id')
        batch_op.drop_column('meta_data')

    # ### end Alembic commands ###
