"""Add deleted_at to MyMemo for soft delete

Revision ID: cc0886a65599
Revises: d12b04acb0e1
Create Date: 2026-01-17 17:10:58.667498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0886a65599'
down_revision = 'd12b04acb0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mymemo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mymemo_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mymemo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mymemo_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
