"""Add title field to MyMemo for topic grouping

Revision ID: d12b04acb0e1
Revises: 1bdf6a23c6e2
Create Date: 2026-01-12 22:01:52.288510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12b04acb0e1'
down_revision = '1bdf6a23c6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mymemo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_mymemo_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mymemo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mymemo_title'))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
