"""Add image_filename and file_filename to MyMemo

Revision ID: d178102da929
Revises: 5787d119892c
Create Date: 2024-08-19 07:52:24.911856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd178102da929'
down_revision = '5787d119892c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_memo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_memo', schema=None) as batch_op:
        batch_op.drop_column('file_filename')
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
