"""Add html_template field to TestResult

Revision ID: d4b51d8254f3
Revises: cc0886a65599
Create Date: 2026-02-10 14:12:42.281970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b51d8254f3'
down_revision = 'cc0886a65599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_template', sa.Text(), nullable=True, comment='완성된 HTML 템플릿'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_column('html_template')

    # ### end Alembic commands ###
