"""Add category and api JSON columns to Product

Revision ID: f12c9c4d0f90
Revises: cdd361bb54dc
Create Date: 2026-01-03 12:34:03.368155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12c9c4d0f90'
down_revision = 'cdd361bb54dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mind_map')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('api', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('api')
        batch_op.drop_column('category')

    op.create_table('mind_map',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.Column('share_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_id')
    )
    # ### end Alembic commands ###
